#!/bin/bash
# Quick deployment guide for remaining 9 Arizona counties
# Created: 2026-01-25
# Status: 6/15 counties deployed (40%)

echo "==========================================="
echo "Arizona Remaining Counties Deployment Guide"
echo "==========================================="
echo ""
echo "STATUS: 6/15 counties deployed (Maricopa, Pima, Pinal, Yavapai, Yuma, Cochise)"
echo "REMAINING: 9 counties"
echo ""

# High Priority Counties
echo "--- HIGH PRIORITY (3 counties) ---"
echo ""
echo "1. NAVAJO COUNTY (~100K parcels estimated)"
echo "   Portal: https://open-data-ncaz.hub.arcgis.com/"
echo "   Action: Browse portal → Search 'parcels' → Extract FeatureServer URL"
echo "   Example: https://services.arcgis.com/.../Parcels/FeatureServer/0"
echo "   Deploy: python3 scripts/download_and_deploy.py --url <ENDPOINT> --name navajo"
echo ""

echo "2. COCONINO COUNTY (~150K parcels estimated)"
echo "   Portal: https://data-coconinocounty.opendata.arcgis.com/"
echo "   Contact: GIS@coconino.az.gov"
echo "   Action: Browse portal → Search 'parcels' → Download or get API"
echo "   Note: Largest county by area (18,661 sq mi)"
echo ""

echo "3. MOHAVE COUNTY (213K population)"
echo "   Portal: https://az-mohave.opendata.arcgis.com/"
echo "   Alt endpoint: Try https://mcgis.mohave.gov/arcgis/rest/services/Mohave/MapServer"
echo "   Note: Previous endpoint timed out, may need IT contact"
echo ""

# SEAGO Regional Group
echo "--- SEAGO COUNTIES (3 counties) ---"
echo ""
echo "4-6. GRAHAM, GREENLEE, SANTA CRUZ"
echo "     Organization: SouthEastern Arizona Governments Organization"
echo "     Website: https://www.seago.org/maps-and-gis-resources"
echo "     Action: Email SEAGO for bulk access to all 3 counties"
echo "     Note: May have regional data portal"
echo ""

# Manual Outreach Needed
echo "--- MANUAL OUTREACH (3 counties) ---"
echo ""
echo "7. APACHE COUNTY (66K population)"
echo "    Web App: https://www.arcgis.com/apps/webappviewer/?id=2fdb74d76b734d4c98869038eae12aea"
echo "    Action: Inspect app → Find REST endpoint OR email county GIS"
echo ""

echo "8. GILA COUNTY (53K population)"
echo "    Website: https://www.gilacountyaz.gov/government/county_manager/contact_us.php"
echo "    Action: Email county manager or GIS department"
echo ""

echo "9. LA PAZ COUNTY (16K population)"
echo "    Previous Portal: https://gis.lapazcountyaz.org/ (404 error)"
echo "    Action: Contact county IT department for new portal URL"
echo ""

echo ""
echo "==========================================="
echo "QUICK DEPLOYMENT WORKFLOW"
echo "==========================================="
echo ""
echo "Once you have an endpoint:"
echo ""
echo "1. Test endpoint and get count:"
echo "   curl '<ENDPOINT>/query?where=1=1&returnCountOnly=true&f=json'"
echo ""
echo "2. Download with parallel workers:"
echo "   python3 << 'PYTHON'"
echo "   import requests, json, time"
echo "   from pathlib import Path"
echo "   from concurrent.futures import ThreadPoolExecutor"
echo "   # [Use download script from deploy_arizona_counties.py]"
echo "   PYTHON"
echo ""
echo "3. Convert to PMTiles:"
echo "   tippecanoe -o parcels_az_<county>.pmtiles -zg --force \\"
echo "     --drop-densest-as-needed --extend-zooms-if-still-dropping \\"
echo "     -l parcels parcels_az_<county>.geojson"
echo ""
echo "4. Upload to R2:"
echo "   python3 scripts/upload_to_r2_boto3.py parcels_az_<county>.pmtiles"
echo ""
echo "5. Update tracking:"
echo "   - Add to data/valid_parcels.json"
echo "   - Update data/coverage_status.json"
echo "   - Regenerate coverage report"
echo ""

echo ""
echo "==========================================="
echo "ALTERNATIVE: REGRID DATA"
echo "==========================================="
echo ""
echo "Purchase all 15 AZ counties from Regrid:"
echo "  https://app.regrid.com/store/us/az/buy"
echo ""
echo "Pros:"
echo "  - Instant access to all counties"
echo "  - Standardized schema across all counties"
echo "  - Regular updates"
echo "  - Quality control"
echo ""
echo "Cons:"
echo "  - Cost per county or statewide"
echo "  - License restrictions"
echo ""

echo ""
echo "==========================================="
echo "CONTACT RESOURCES"
echo "==========================================="
echo ""
echo "AGIC (Arizona Geographic Information Council):"
echo "  Phone: (602) 364-3747"
echo "  Email: agic_info@azland.gov"
echo "  County Contacts: https://agic.az.gov/resources (interactive map)"
echo ""
echo "AZGeo Data Hub:"
echo "  https://azgeo-data-hub-agic.hub.arcgis.com/"
echo ""

echo ""
echo "Next Steps:"
echo "  1. Start with Navajo County (easiest - portal accessible)"
echo "  2. Then Coconino County (largest by area)"
echo "  3. Batch request SEAGO counties (3 at once)"
echo "  4. Email individual counties for remaining 3"
echo ""
echo "Target: 100% Arizona coverage within 2-3 weeks"
echo ""
